version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/www
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    links:
     - "web:epweb"
  mongo:
    container_name: echopig-mongo
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - mongo:/data/db
     - ./data/mongo/mongo-setup.sh:/docker-entrypoint-initdb.d/mongo-setup.sh:ro
    restart: always
    env_file:
    - .env.dev
  mongo-express:
    image: mongo-express
    ports:
     - "8081:8081"
    links:
     - mongo
    env_file:
    - .env.dev
  web:
    build: 
      context: .
      dockerfile: Dockerfile-dev
    image: epweb:latest
    restart: always
    ports:
     - "9001:9001"
     - "9229:9229"
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
    depends_on:
      - mongo
    command:
      - npm
      - run
      - dev 

volumes:
  mongo: