version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: ngingx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/www
      # - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    links:
     - "web:epweb"
  db:
    container_name: echopig-mongo
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - mongo:/data/db
  web:
    build: .
    image: epweb:latest
    ports:
     - "9001:9001"
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
    environment:
      - ENV=production
      - NODE_ENV=production
    depends_on:
      - db

volumes:
  mongo: