version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/www
      - /docker-volumes/etc/letsencrypt:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    logging:
      driver: awslogs
      options:
        awslogs-group: "ep-nginx"
        awslogs-region: "us-east-1"
    links:
     - "web:epweb"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  web:
    build: .
    image: epweb:latest
    ports:
     - "9001:9001"
    restart: always
    environment:
      ENV: production
      NODE_ENV: production
    env_file:
     - .env
    logging:
      driver: awslogs
      options:
        awslogs-group: "epweb"
        awslogs-region: "us-east-1"
