version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/www
      # - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      # - 443:443
    links:
     - "web:epweb"
  mongo:
    container_name: echopig-mongo
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - mongo:/data/db
  mongo-express:
    image: mongo-express
    ports:
     - "8081:8081"
    links:
     - mongo
  web:
    build: .
    image: epweb:latest
    ports:
     - "9001:9001"
     - "9229:9229"
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
    depends_on:
      - mongo
    command:
      - npm
      - run
      - dev 

volumes:
  mongo: