version: '3'
services:
  db:
    container_name: echopig-mongo
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - mongo:/data/db
  web:
    build: .
    image: epweb:latest
    ports:
     - "9001:9001"
     - "9229:9229"
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
    depends_on:
      - db
    command:
      - npm
      - run
      - dev 

volumes:
  mongo: